language: perl
perl:
  - "5.18"
  - "5.14"
  - "5.10"
branches:
  only:
    - /^build/
    - /^releases/
before_install:
  - cpanm -n Devel::Cover::Report::Coveralls
  - dzil authordeps --missing | xargs -n 5 -P 10 cpanm --notest
  - export AUTOMATED_TESTING=1 RELEASE_TESTING=1 AUTHOR_TESTING=1
  - export HARNESS_OPTIONS=c HARNESS_TIMER=1 HARNESS_VERBOSE=1
script:
  perl Makefile.PL && make && cover -test -report coveralls
